### ISSUE TITLE
New Object List

### ISSUE THREAD

**Issue by edvardodegaard** [gomegaminds/hubs#110]
Need a new object list for the Classroom Editor, without sidebar squishing everything.

**Comment by SpaceBeing1** [comment]
Adding to this... yes, we need the ability to select objects in the Classroom Editor.  I placed a music track in a wall to hide the icon, and now there is no way to reposition the track.

**Comment by edvardodegaard** [comment]
https://github.com/gomegaminds/hubs/pull/199

Added in latest release. It currently replaces the watermark, as the watermark is messy and redundant for screen estate and in the same place as user list.
