### ISSUE TITLE
Text Bug

### ISSUE THREAD

**Issue by SpaceBeing1** [gomegaminds/hubs#119]
If you change the color of text and then close out of the text editor without creating it, the next time you open up the text component, you are unable to change the color of the text.

**Comment by edvardodegaard** [comment]
Not able to reproduce.

Steps attempted:
- Click "Add Text Component" button in Classroom Editor
- Open the color picker, Change the color of the text by clicking on one of the colors
- Directly after changing color click the "X" button while the color picker is still open
- Click the "Add Text Component" button in Classroom Editor
- Open the color picker, change the color of the text (here is when I expect something to not work, however i can change the color just fine)

Tested in Firefox and Chrome

**Comment by edvardodegaard** [comment]
Closed due to inactivity, new system is implemented so please re-raise the issue if it still exists.
