### ISSUE TITLE
Add tip of how to right click

### ISSUE THREAD

**Issue by SpaceBeing1** [gomegaminds/hubs#120]
![Screenshot 2022-11-02 102422](https://user-images.githubusercontent.com/111762850/199515061-1a291003-29b5-48fb-9548-46c8c36baae4.png)

In Classroom Editor, move the Edit text to the bottom.  Then beneath that in a smaller font:

Two finger tap or Control-click on Mac or Alt-click on Chromebook 

Add this as well to the tips on the regular UI.

**Comment by edvardodegaard** [comment]
We want related functionality to be grouped together for best possible user experience. That means look and edit (both relating to mouse button) should be next to each other. As well as keeping hierarchy of importance (uploading content is the least important)

I have implemented browser detection to tailor the help text specifically to mac or android(chromebook) users, without confusing other users on different OS. Also improved the readability slightly in new update coming out in 5 min.
