### ISSUE TITLE
Audio autoplays

### ISSUE THREAD

**Issue by SpaceBeing1** [gomegaminds/hubs#166]
Audio seems to auto play upon entering a room.  It is inconsistent however. For some files it seems to auto play, for others it does not.

**Comment by edvardodegaard** [comment]
Please wait with bug reports on elements such as video, audio, youtube, text, etc. until the QA tests are done and the new system is live, as we are completely revamping them and all the bug reports will be outdated when the new systems are coming out.

On that note we will also be implementing an "autoplay" toggle on most stuff like video, audio, youtube video, etc. to allow the user to select if the content should be autoplayable or not when entering a room.
