### ISSUE TITLE
Classrooms not maintaining integrity

### ISSUE THREAD

**Issue by SpaceBeing1** [gomegaminds/hubs#181]
Some content for my Same Here classroom has dissapeared somehow

<img width="968" alt="image" src="https://user-images.githubusercontent.com/111762850/213078147-8fd917c7-b252-46ad-a3de-09b82e40af43.png">

I've also noticed that some posters and other items have shifted very slightly, but enough that it required correction.  Do you know what's going on here?

**Comment by edvardodegaard** [comment]
Were they moveable? Are you sure nobody just dragged them into the wall?
From what I recall you allow them to be moved by other users, which can result in this..

**Comment by SpaceBeing1** [comment]
You are correct, they were inside the walls.  But no one had moved them.  This must be related to the other posters that had moved slightly.

In regards to students being allowed to move them, wouldn't they return to the original place after the student had left the room?

**Comment by SpaceBeing1** [comment]
Update: I corrected the posters that were hidden in the wall, but then the next time I entered the room again they reverted back to being inside the walls.
![Screenshot 2023-01-18 164648](https://user-images.githubusercontent.com/111762850/213302221-f1425350-6971-4fd6-b774-61802d2400e6.jpg)

**Comment by SpaceBeing1** [comment]
Ok, something weird is going on... just did another test and the same thing happened and the settings I applied to the poster (i.e. no grabbable) were reset.  It was as though those posters just ignored everything I did to them and reverted back into their default position in the wall and object settings.

**Comment by edvardodegaard** [comment]
It was because you had "students can move" disabled, and presumably was not logged onto the correct account, so the changes were not permanent. Same for me. I will investigate a mismatch in the backend on permissions later, might need some fixing on edge cases, or at least tell the menus that they dont have permission. The room is fixed now.
