### ISSUE TITLE
Mobile instability

### ISSUE THREAD

**Issue by SpaceBeing1** [gomegaminds/hubs#187]
I am unable to explore the SameHere Global room on mobile.  After a few seconds I get this message:

![Screenshot_20230118-120818_Chrome](https://user-images.githubusercontent.com/111762850/213276092-c96aba9c-89d3-4561-b9c4-73df9255086b.jpg)

Here is the room:  https://megaminds.world/jaycSHM/samehere-global

**Comment by SpaceBeing1** [comment]
This is urgent to fix as I plan using this room to demo with next week at FETC and there will be many mobile demos.

**Comment by edvardodegaard** [comment]
Most likely your phone is running out of memory. This is something I cannot control or fix as the phone is the one deciding to crash. If the issue does not go away after cleaning the room size / complex objects, please re-open this issue.
