### ISSUE TITLE
Chichen Itza room additions

### ISSUE THREAD

**Issue by SpaceBeing1** [gomegaminds/hubs#192]
Search GIFs under "Mayan Temple" to find this one.
![Screenshot 2023-01-19 095458](https://user-images.githubusercontent.com/111762850/213474975-13cc2515-1194-4566-a7ee-e56f217dea59.png)

Add "Discussion Room" over door
![Screenshot 2023-01-19 095618](https://user-images.githubusercontent.com/111762850/213475321-7618429f-41b7-4432-8096-d53c7fd4ab4e.png)

Add text to the object wall
![Screenshot 2023-01-19 095821](https://user-images.githubusercontent.com/111762850/213475857-8654a611-2a63-461b-b436-ba0e5e74cd63.png)

**Comment by edvardodegaard** [comment]
Done. Follow up permission bugs on #191
