### ISSUE TITLE
Sketchfab Objects are not permanent

### ISSUE THREAD

**Issue by SpaceBeing1** [gomegaminds/hubs#209]
3D objects placed in rooms are not permanent and disappear when I later return to the room.  Other object types (videos, GIFs, text) seem to be behaving normally.  

I have encountered this bug in two ways:

- Creating a teacher focused room, when I add 3D objects they disappear.
- Creating a student focused room, when students add 3D objects they disappear.

**Comment by edvardodegaard** [comment]
Able to repro only on sketchfab models, normal glb / gltf files work fine. Probably something on sketchfab / hubs api changed. Looking into it tomorrow.

**Comment by edvardodegaard** [comment]
Fixed, swapped upload code for sketchfab to new system with objectHelper
