### ISSUE TITLE
URGENT - YouTube Videos and Assessment Questions show up as broken links even though they are still functioning

### ISSUE THREAD

**Issue by SpaceBeing1** [gomegaminds/hubs#243]
I believe this is likely a simple bug to fix, but I am unable to complete my onboarding videos until it is fixed.  Thx!

**Comment by edvardodegaard** [comment]
Please post a picture or a link to the room, I cannot reproduce this error

**Comment by edvardodegaard** [comment]
Nevermind I think I know whats wrong!

**Comment by edvardodegaard** [comment]
Updated links to new server
