### ISSUE TITLE
student email verification bug

### ISSUE THREAD

**Issue by SpaceBeing1** [gomegaminds/hubs#43]
**Description**
After the student signs in, the “You Are Now Signed In” notification stays on screen and you are unable to click it off.

**To Reproduce**
1. click on a link assigned by a teacher
2. try and pin an object
3. verify your email

**Screenshots**
![Screenshot 2022-09-04 231756](https://user-images.githubusercontent.com/111762850/188354154-f1b0fadb-b693-4693-9381-788c43afeea6.jpg)

**Comment by camelgod** [comment]
Clicking "continue" and the "X" works fine for me, it closes the menu as expected, both while un-pinning and pinning.

Any circumstances in the room to reproduce this? For example if you turned on / off "pin objects" permission in room settings etc?

**Comment by SpaceBeing1** [comment]
was unable to reproduce.  Must've been a one time bug.  Closing issue
