### ISSUE TITLE
Student Tools Icon

### ISSUE THREAD

**Issue by SpaceBeing1** [gomegaminds/hubs#44]
Can we use a hammer or a pick axe or something?

![Screenshot 2022-09-04 233527](https://user-images.githubusercontent.com/111762850/188355798-137221d6-b971-4573-8eaa-c7a5322e10a7.jpg)

**Comment by camelgod** [comment]
Hammer or pickaxe would imply something to do with crafting and inside 3D world and resembles too much in-"game" functionality in my opinion. What would be the purpose/motivation of changing the icon? The point of this menu is to contain all the functions that are related to dashboard stuff and non-immersive functionality for a student. I would like to steer away from gamified icons when it comes to the dashboard.

Alternatively make a new issue describing what other student tools are on the wishlist, and then we can see if it is useful to create a new crafting tool menu, change the existing student menu, or spread them out like the other buttons already on the menu.

**Comment by SpaceBeing1** [comment]
hmm... I think I'm just not a fan of the student in a cap icon.  Could we try something like this?
![676278_pencil_512x512](https://user-images.githubusercontent.com/111762850/188771752-624faf88-7875-45d8-a184-834f3ccdb918.png)

**Comment by camelgod** [comment]
What about playing with the contents of the actual menu? Right now we have only "submit photo" button. I can make a custom icon for us including a camera, pencil, and some other stuff.

What would we like to have inside this menu in the future? I think that should point us to a good icon to let the user better know whats inside the submenu.

**Comment by SpaceBeing1** [comment]
I'm not sure what we will have in the future, but actually since we don't have any items yet maybe we should just have the submit photo button and no menu for now?  Much more straightforward that way, and it's apparent right away that there is a way to capture and submit work.

**Comment by edvardodegaard** [comment]
Discussed during meeting, leaving it for now and adding more features soon. Will keep this open until we have a new icon :)
