### ISSUE TITLE
Object controls in Classroom Editor

### ISSUE THREAD

**Issue by camelgod** [gomegaminds/hubs#45]
Need to test and migrate the Spoke controls as the threejs transformcontrol library not working optimally.

- [ ] Snapping functionality (like spoke)
- [ ] Straight planes (like spoke)
- [ ] Pre allocated media frames (we can add this in our "Worlds")
- [ ] Gizmo for transform controls (click and drag to move, scale, rotate)
- [ ] Automatic pinning / make it not a thing you even think about. Remove animation, remove pin buttons

**Comment by camelgod** [comment]
Meet with Roman on Monday to discuss raycasting / layering issue

**Comment by edvardodegaard** [comment]
Closing this for now as we have overhauled both pinning, placement and manipulation.
