### ISSUE TITLE
Remove 'sign in to pin objects' notification

### ISSUE THREAD

**Issue by SpaceBeing1** [gomegaminds/hubs#72]
![Screenshot 2022-09-20 140556](https://user-images.githubusercontent.com/111762850/191332066-9d445432-0d3b-45aa-b416-ab3371c58b59.png)

**Comment by edvardodegaard** [comment]
Where / how did this pop up?
You should technically always be signed in if you are in a classroom.

is this inside of a session?

**Comment by edvardodegaard** [comment]
Fixed.

We can talk about sessions/classrooms and permanence in todays meeting.
