### ISSUE TITLE
Email best practices and communication for teachers that are on restrictive networks

### ISSUE THREAD

**Issue by edvardodegaard** [gomegaminds/hubs#76]
Check dkim signing on outgoing emails

**Comment by SpaceBeing1** [comment]
These are the school emails that are not accepting confirmation emails from the Hubs client so far:

parmacityschools.org
schools.nyc.gov

**Comment by edvardodegaard** [comment]
DKIM Signing was already set up for the megaminds.world identity in AWS.

I have changed the hubs-sign-in-verification email to include the legal address, hopefully that will make it even more ok for spam filters.

@SpaceBeing1 Are you able to test with a teacher, to check if this new text with the address changes anything?

Other than that, there is not much we can do except reach out and communicate. For example if a school is actively blocking all .world domains, we cannot perform any action to avoid that.

Future action points for this issue:
- [ ] Change text in the Verify Email box to say something about "If you do not receive it, check spam folder, talk to IT department, refer to documentation"
- [ ] (Prerequisite) Need documentation page up and running

**Comment by SpaceBeing1** [comment]
So, interesting thing happens when someone with a schools.nyc.gov email tries to create an account I receive a something went wrong error... strange

<img width="382" alt="Screen Shot 2022-09-22 at 9 16 31 PM" src="https://user-images.githubusercontent.com/111762850/191876521-5e50ff7d-60fd-4782-ae65-4d969a0c157b.png">

**Comment by edvardodegaard** [comment]
Need to differenciate between email sent from Hubs (this issue) and auth0/dashboard signups. They are two different systems, and for all we know this can be an internal auth0 error unrelated to the nyc.gov email receive system

**Comment by edvardodegaard** [comment]
This should be fine now with new onboarding flow, auth0 templates and email backend, and hubs settings
