### ISSUE TITLE
Right-click context menu instead of spacebar

### ISSUE THREAD

**Issue by edvardodegaard** [gomegaminds/hubs#78]
Users have a hard time finding and understanding the spacebar button.

Its clunky to hold down and perform actions at the same time, and its not best practice for accessibility either (for example if you only have motion in one hand, or using input devices that do not allow for multiple actions at the same time (some laptops/windows settings even go as far as to only allow you to use trackpad or keyboard, not both).

The most intuitive and interesting path in my opinion is to change the right click functionality into a menu system that do not require multiple simultaneous inputs, and does not rely on keyboard action (but we should optionally have an alternative keyboard button to bring up this menu in case someone is using a non-mouse setup)

We can incorporate a help-text on hover like @SpaceBeing1 suggested in #77

**Comment by SpaceBeing1** [comment]
Just so I'm clear, is the context menu the same thing as what i'm referring to as the Hover menu (the pink menu)?

**Comment by edvardodegaard** [comment]
> Just so I'm clear, is the context menu the same thing as what i'm referring to as the Hover menu (the pink menu)?

Right now the "context menu" for objects is the spacebar pink menu. 
In this issue I am proposing to move it from spacebar into a rightclick menu together with a redesign

https://en.wikipedia.org/wiki/Context_menu
