### ISSUE TITLE
Change copy on the Student Input button in the Classroom Editor

### ISSUE THREAD

**Issue by SpaceBeing1** [gomegaminds/hubs#81]
Change the button name to "Add Question"

Change the description copy to "Add assessment questions to your classroom. The results will show up in the teacher dashboard."

![Screenshot 2022-09-22 182058](https://user-images.githubusercontent.com/111762850/191861828-d09aaebb-5986-4014-97a8-4556eb9dcf42.jpg)

**Comment by edvardodegaard** [comment]
Fixed in next release
