### ISSUE TITLE
New Popover Menus for Toolbar

### ISSUE THREAD

**Issue by SpaceBeing1** [gomegaminds/hubs#87]
![Screenshot 2022-10-10 094442](https://user-images.githubusercontent.com/111762850/194902450-471259ff-2114-441e-a99c-839c324a9858.png)

![Screenshot 2022-10-10 094426](https://user-images.githubusercontent.com/111762850/194902463-6b3aaa76-90b7-4aab-b54b-a20efd28ade3.png)

**Comment by edvardodegaard** [comment]
Aware of this, will be fixed once we move from Mozilla to our own popover menu system
