### ISSUE TITLE
Change Sketchfab name to 3D Models in content library

### ISSUE THREAD

**Issue by SpaceBeing1** [gomegaminds/hubs#90]
![Screenshot 2022-10-16 153805](https://user-images.githubusercontent.com/111762850/196054694-ce4d853f-9f9d-4f6c-adb3-98c54d314e99.png)

Search bar text would also need to be changed.  
Can we also remove 'Videos' and 'Images' as well, so it's just 3D Models and GIFs?

**Comment by edvardodegaard** [comment]
#106 
Need to redo the whole browser system as its way too messy inheriting all the stuff from Hubs. Better to just remake it with our new systems.
