### ISSUE TITLE
Classroom Editor Onboarding

### ISSUE THREAD

**Issue by edvardodegaard** [gomegaminds/hubs#92]
-

**Comment by SpaceBeing1** [comment]
Add a 'walkthrough' with pop ups that show teachers the main features of the Classroom Editor and the Object Menu.
We should add a persistent 'view walkthrough' button for Classroom Editor.
Example:

![Screenshot 2022-10-23 231136](https://user-images.githubusercontent.com/111762850/197441396-a349e989-ad27-41c9-b23e-f3fbe938b105.png)

**Comment by edvardodegaard** [comment]
Already started an implementation that I showcased in an earlier meeting. Should be good to go sometime next week hopefully.
